{{- if .Values.observantio.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "observantio.fullname" . }}-observantio
  labels:
    {{- include "observantio.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.observantio.replicaCount }}
  selector:
    matchLabels:
      {{- include "observantio.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: observantio
  template:
    metadata:
      labels:
        {{- include "observantio.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: observantio
    spec:
      automountServiceAccountToken: {{ .Values.hardening.automountServiceAccountToken }}
      securityContext:
        {{- toYaml .Values.hardening.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "observantio.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: observantio
        image: "{{ .Values.observantio.image.repository }}:{{ .Values.observantio.image.tag }}"
        imagePullPolicy: {{ .Values.observantio.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.observantio.service.port }}
          name: http
        env:
        {{- range $k, $v := .Values.observantio.env }}
        - name: {{ $k }}
          value: {{ tpl ($v | toString) $ | quote }}
        {{- end }}
        envFrom:
        - secretRef:
            name: {{ include "observantio.fullname" . }}-secrets
        livenessProbe:
          httpGet:
            path: {{ .Values.observantio.probes.path }}
            port: http
          initialDelaySeconds: {{ .Values.observantio.probes.initialDelaySeconds }}
          periodSeconds: {{ .Values.observantio.probes.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.observantio.probes.path }}
            port: http
          initialDelaySeconds: {{ .Values.observantio.probes.initialDelaySeconds }}
          periodSeconds: {{ .Values.observantio.probes.periodSeconds }}
        resources:
          {{- toYaml .Values.observantio.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.hardening.containerSecurityContext | nindent 10 }}
{{- end }}
