server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # SPA fallback
  location / {
    try_files $uri $uri/ /index.html;
  }

  # No-cache for HTML/manifest/json
  location ~* \.(?:manifest|appcache|html?|xml|json)$ {
    add_header Cache-Control "no-cache, must-revalidate";
  }

  # Long cache for static assets
  location ~* \.(?:css|js|woff2?|ttf|eot|otf|jpg|jpeg|png|gif|svg|ico)$ {
    try_files $uri =404;
    expires 1y;
    access_log off;
    add_header Cache-Control "public";
  }
}
